experiment:
  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/splitting/0/0/train.tsv
    validation_path: ../data/{0}/splitting/0/0/val.tsv
    test_path: ../data/{0}/splitting/0/test.tsv
  dataset: douban

  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:

    Random:
      meta:
        save_recs: False
        verbose: False
      seed: 42

    MostPop:
      meta:
        save_recs: False
        verbose: False

    ItemKNN:
      meta:
        save_recs: False
        verbose: False
      neighbors: 951
      asymmetric_alpha: 1.728255830929901
      tversky_alpha: 1.766630554761724
      tversky_beta: 1.6747767111065683
      similarity: jaccard

    EASER:
      meta:
        save_recs: False
        verbose: False
      l2_norm: 3640.270951670678
      neighborhood: -1

    RP3beta:
      meta:
        save_recs: False
        verbose: False
      neighborhood: 1246
      alpha: 0.6972518663686161
      beta: 0.6217594853017056
      normalize_similarity: True

    external.FPSR:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64  # only for evaluation
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 0.1
      eps: 5e-3
      tau: 0.5
      seed: 2026

    external.GFCF:
      meta:
        save_recs: False
        verbose: False
      batch_eval: 1024
      svd_factors: 256
      alpha: 0.21948822034403112
      seed: 2026

    external.FPSRplus:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 128
      batch_size: 64
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 1.0
      eps: 5e-3
      tau: 0.4
      pop_ratio: 0.1
      seed: 2026

    external.FPSRplusF:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.5
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 0.1
      eps: 5e-3
      tau: 0.4
      pop_ratio: 0.1
      seed: 2026

    external.LightGCN:
      meta:
        verbose: False
        save_weights: False
        validation_metric: Recall@20
      lr: 0.001
      epochs: 1000
      factors: 64
      batch_size: 2048
      l_w: 0.00023264527491463817
      n_layers: 4
      normalize: True
      seed: 42

    external.BISM:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
      alpha: 0.08422832997467446
      beta: 69.31627111404818
      lamb: 44.099661193160514
      epochs: 12
      batch_size: 2048
      c: 4