experiment:
  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/splitting/0/0/train.tsv
    test_path: ../data/{0}/splitting/0/test_tail.tsv
  dataset: gowalla

  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:
    external.FPSR:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.4
      rho: 500
      w_1: 1.0
      w_2: 5.0
      eta: 0.1
      eps: 5e-3
      tau: 0.2
      seed: 2026
    external.FPSRplus:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.2
      rho: 500
      w_1: 0.8
      w_2: 5.0
      eta: 0.1
      eps: 5e-3
      tau: 0.4
      pop_ratio: 0.1
      seed: 2026
    external.FPSRplusF:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.4
      rho: 500
      w_1: 0.5
      w_2: 5.0
      eta: 1.0
      eps: 5e-3
      tau: 0.5
      pop_ratio: 0.1
      seed: 2026
    external.BISM:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        validation_rate: 7
      alpha: 0.08422832997467446
      beta: 69.31627111404818
      lamb: 44.099661193160514
      epochs: 7
      batch_size: 2048
      c: 4