experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_fpsr.tsv
    test_path: ../data/{0}/test_fpsr.tsv
    validation_path: ../data/{0}/valid_fpsr.tsv
  dataset: douban
  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        save_recs: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.2
      rho: 500
      w_1: 0.8
      w_2: 0.1
      eta: 1.0
      eps: 5e-3
      tau: 0.5
      seed: 2026