experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_fpsr.tsv
    test_path: ../data/{0}/test_fpsr.tsv
    validation_path: ../data/{0}/valid_fpsr.tsv
  dataset: yelp2018
  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        save_recs: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.5
      rho: 10000
      w_1: 0.6
      w_2: 2.0
      eta: 0.1
      eps: 4e-3
      tau: 0.3
      seed: 2026