experiment:
  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/splitting/0/0/train.tsv
    validation_path: ../data/{0}/splitting/0/0/val.tsv
    test_path: ../data/{0}/splitting/0/test.tsv
  dataset: douban

  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:

    external.FPSR:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 0.1
      eps: 5e-3
      tau: [0.5,0.05,0.15,0.25]
      seed: 2026

    external.FPSRplus:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 128
      batch_size: 64
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 1.0
      eps: 5e-3
      tau: [0.4,0.05,0.15,0.25]
      pop_ratio: 0.1
      seed: 2026

    external.FPSRplusF:
      meta:
        save_recs: False
        verbose: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.5
      rho: 500
      w_1: 1.0
      w_2: 1.0
      eta: 0.1
      eps: 5e-3
      tau: [0.4,0.05,0.15,0.25]
      pop_ratio: 0.1
      seed: 2026